"""create MaterialCode models

Revision ID: 1c17141a06b9
Revises: 
Create Date: 2024-10-15 21:28:00.744390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c17141a06b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_codes')
    # ### end Alembic commands ###
