"""Add Column created_at to stock model

Revision ID: 2f12c1dde77a
Revises: 3baa78ba6ca6
Create Date: 2024-11-25 05:23:54.753859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f12c1dde77a'
down_revision: Union[str, None] = '3baa78ba6ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'created_at')
    # ### end Alembic commands ###
