"""add column areamodel created_by_id

Revision ID: 3b60313ecf85
Revises: 25cad2338f26
Create Date: 2024-12-01 21:20:20.790991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b60313ecf85'
down_revision: Union[str, None] = '25cad2338f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'areas', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'created_by_id')
    # ### end Alembic commands ###
