"""Add Column file_name to certpass_model

Revision ID: 3baa78ba6ca6
Revises: 2784a12c8208
Create Date: 2024-11-20 12:17:21.739098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3baa78ba6ca6'
down_revision: Union[str, None] = '2784a12c8208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certpass_models', sa.Column('file_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certpass_models', 'file_name')
    # ### end Alembic commands ###
