"""add column project_id to unusable and service models

Revision ID: 404c9c9b3857
Revises: 1a49b34b1c15
Create Date: 2024-12-12 21:06:46.068463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404c9c9b3857'
down_revision: Union[str, None] = '1a49b34b1c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('service_materials', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_materials', 'projects', ['project_id'], ['id'])
    op.add_column('unusable_materials', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unusable_materials', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unusable_materials', type_='foreignkey')
    op.drop_column('unusable_materials', 'project_id')
    op.drop_constraint(None, 'service_materials', type_='foreignkey')
    op.drop_column('service_materials', 'project_id')
    op.alter_column('areas', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
