"""change column in stock model qty with quantity

Revision ID: 7eeaf1b20709
Revises: a26d5d03a068
Create Date: 2024-10-25 13:46:43.158965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eeaf1b20709'
down_revision: Union[str, None] = 'a26d5d03a068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('quantity', sa.Float(), nullable=True, default=0))
    # op.execute('update stocks set quantity=qty')
    op.drop_column('stocks', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('stocks', 'quantity')
    # ### end Alembic commands ###
