"""relationship user and project model

Revision ID: ce32094b1de7
Revises: 03d3689525e6
Create Date: 2024-10-15 22:36:14.581840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce32094b1de7'
down_revision: Union[str, None] = '03d3689525e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'project_id')
    # ### end Alembic commands ###
