"""Add Column UserModel to group_id

Revision ID: e32b336bb7d4
Revises: 85c7c5e9840d
Create Date: 2024-11-18 14:04:28.470854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32b336bb7d4'
down_revision: Union[str, None] = '85c7c5e9840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], ['id'])
    op.drop_constraint('warehouse_materials_group_id_fkey', 'warehouse_materials', type_='foreignkey')
    op.drop_column('warehouse_materials', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_materials', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('warehouse_materials_group_id_fkey', 'warehouse_materials', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###
